
[[characters]]
name = "Malfaz Zoleum"
username = "gogoGhost"
alias = "gg"
replacements = [["^", "☾"], ["$", "☽"]]
color = "0x000000"
image_url = "https://gitlab.com/ad-astra-hs/karxbot/-/raw/main/sprites/Malfaz%20Zoleum.png?ref_type=heads"
emoji = "<:MalfazZoleum:1327671682936340591>"
case = "inverted"

[[characters]]
name = "Jozlyn Caluma"
username = "phantasmataVisage"
alias = "pv"
replacements = [["^", "⭂{"], ["$", "}⥵"]]
color = "0xA10000"
image_url = "https://gitlab.com/ad-astra-hs/karxbot/-/raw/main/sprites/Jozlyn%20Caluma.png?ref_type=heads"
emoji = "<:JozlynCaluma:1327671634575757486>"
case = "title"

[[characters]]
name = "Febrez Galvan"
username = "ancientAutomata"
alias = "aa"
replacements = [["^|$", " ⚙️ "], ["E", "3"], ["OO", "oOo"]]
color = "0xA15000"
image_url = "https://gitlab.com/ad-astra-hs/karxbot/-/raw/main/sprites/Febrez%20Galvan.png?ref_type=heads"
emoji = "<:FebrezGalvan:1327671624266420234>"
case = "upper"

[[characters]]
name = "Mixiek Kakkki"
username = "sylphesterStallone"
alias = "ss"
replacements = [
    [
        "s|S",
        "$",
    ],
    [
        "\"|,",
        ",,",
    ],
    [
        "\\.|'",
        ",",
    ],
    [
        "(.+? .+?)( .+)",
        "$1,,$2",
    ],
]
color = "0xA1A100"
image_url = "https://gitlab.com/ad-astra-hs/karxbot/-/raw/main/sprites/Mixiek%20Kakkki.png?ref_type=heads"
emoji = "<:MixiekKakkki:1327671694365687888>"
case = "lower"

[[characters]]
name = "Eletra Zolage"
username = "staticRebel"
alias = "sr"
replacements = [["s", "z"], ["S", "Z"], ["l|L", "/"], ["c|C", "<"]]
color = "0xE8E741"
image_url = "https://gitlab.com/ad-astra-hs/karxbot/-/raw/main/sprites/Eletra%20Zolage.png?ref_type=heads"
emoji = "<:EletraZolage:1327671614715855004>"
case = "none"

[[characters]]
name = "Liaaam Galagr"
username = "zombieBastards"
alias = "zb"
replacements = [["[aeiouAEIOU]+", "$0 "]]
color = "0x626262"
image_url = "https://gitlab.com/ad-astra-hs/karxbot/-/raw/main/sprites/Liaaam%20Galagr.png?ref_type=heads"
emoji = "<:LiaaamGalagr:1327671671452074056>"
case = "lower"

[[characters]]
name = "Pennee Lechap"
username = "tousleMimes"
alias = "tm"
replacements = [["[a-zA-Z0-9]+", " ... "]]
color = "0x416600"
image_url = "https://gitlab.com/ad-astra-hs/karxbot/-/raw/main/sprites/Pennee%20Lechap.png?ref_type=heads"
emoji = "<:PenneeLechap:1327671717744611449>"
case = "none"

[[characters]]
name = "Artyis Avelho"
username = "freakinMagic"
alias = "fm"
replacements = [["^", "[ "], ["$", " |###]"]]
color = "0x008141"
image_url = "https://gitlab.com/ad-astra-hs/karxbot/-/raw/main/sprites/Artyis%20Avelho.png?ref_type=heads"
emoji = "<:ArtyisAvelho:1327671589424332962>"
case = "none"

[[characters]]
name = "Lavena Perazi"
username = "druryVigilante"
alias = "dv"
replacements = [["^", "--- "], ["$", " ---O"], ["l", "L"]]
color = "0x008282"
image_url = "https://gitlab.com/ad-astra-hs/karxbot/-/raw/main/sprites/Lavena%20Perazi.png?ref_type=heads"
emoji = "<:LavenaPerazi:1327671662140981278>"
case = "none"

[[characters]]
name = "Karxol Koomaa"
username = "supernovaFruitcake"
alias = "sf"
replacements = [["ck", "%"], ["k|%", "kk"], ["c", "k"], ["$", "."]]
color = "0x005682"
image_url = "https://gitlab.com/ad-astra-hs/karxbot/-/raw/main/sprites/Karxol%20Koomaa.png?ref_type=heads"
emoji = "<:KarxolKoomaa:1327671648861818992>"
case = "lower"

[[characters]]
name = "Tohbra Corrah"
username = "screwedJobber"
alias = "sj"
replacements = [
    [
        "S",
        "%%%",
    ],
    [
        "s",
        "£££",
    ],
    [
        "Z",
        "S",
    ],
    [
        "z",
        "s",
    ],
    [
        "%%%",
        "Z",
    ],
    [
        "£££",
        "z",
    ],
    [
        "^",
        "<{",
    ],
    [
        "$",
        "}<",
    ],
]
color = "0x000056"
image_url = "https://gitlab.com/ad-astra-hs/karxbot/-/raw/main/sprites/Tohbra%20Corrah.png?ref_type=heads"
emoji = "<:TohbraCorrah:1327671731900383242>"
case = "title"

[[characters]]
name = "Birsha Orobas"
username = "solemnProphet"
alias = "sp"
replacements = [["E|e", "Σ"], ["T|t", "✞"], ["$", "~"]]
color = "0x2B0057"
image_url = "https://gitlab.com/ad-astra-hs/karxbot/-/raw/main/sprites/Birsha%20Orobas.png?ref_type=heads"
emoji = "<:BirshaOrobas:1327671606289367090>"
case = "none"

[[characters]]
name = "Tsoray Vodnik"
username = "requiterElite"
alias = "re"
replacements = [
    [
        "\\.",
        ".~",
    ],
    [
        "\\?",
        "?~",
    ],
    [
        "\\!",
        "!~",
    ],
    [
        "$",
        ".~",
    ],
    [
        "A",
        "a",
    ],
    [
        "E",
        "e",
    ],
    [
        "I",
        "i",
    ],
    [
        "O",
        "o",
    ],
    [
        "U",
        "u",
    ],
    [
        "Y",
        "y",
    ],
    [
        "H",
        "h",
    ],
    [
        "\\.~\\.~",
        ".~",
    ],
]
color = "0x6A006A"
image_url = "https://gitlab.com/ad-astra-hs/karxbot/-/raw/main/sprites/Tsoray%20Vodnik.png?ref_type=heads"
emoji = "<:TsorayVodnik:1327671743069949954>"
case = "upper"

[[characters]]
name = "Paiyuu Rowena"
username = "abyssalPedestal"
alias = "ap"
replacements = [["a|A", "☆"]]
color = "0x77003C"
image_url = "https://gitlab.com/ad-astra-hs/karxbot/-/raw/main/sprites/Paiyuu%20Rowena.png?ref_type=heads"
emoji = "<:PaiyuuRowena:1327671705031803002>"
case = "none"
